// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../components/Button.vue')['default']
    ExternalLink: typeof import('./../components/ExternalLink.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    IconMdiGithub: typeof import('~icons/mdi/github')['default']
    IconMdiHeadHeart: typeof import('~icons/mdi/head-heart')['default']
    IconMdiInstagram: typeof import('~icons/mdi/instagram')['default']
    IconMdiReddit: typeof import('~icons/mdi/reddit')['default']
    IconMdiTwitter: typeof import('~icons/mdi/twitter')['default']
    IconRiMoonLine: typeof import('~icons/ri/moon-line')['default']
    IconRiSunLine: typeof import('~icons/ri/sun-line')['default']
    ListPosts: typeof import('./../components/ListPosts.vue')['default']
    ListProjects: typeof import('./../components/ListProjects.vue')['default']
    Navigation: typeof import('./../components/Navigation.vue')['default']
    Post: typeof import('./../components/Post.vue')['default']
    TerminalWindow: typeof import('./../components/TerminalWindow.vue')['default']
    WiggleAnimation: typeof import('./../components/WiggleAnimation.vue')['default']
  }
}

export { }
