/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A4Paper: typeof import('./../components/A4Paper.vue')['default']
    AppLink: typeof import('./../components/AppLink.vue')['default']
    AppSection: typeof import('./../components/AppSection.vue')['default']
    Button: typeof import('./../components/Button.vue')['default']
    Collapsible: typeof import('./../components/Collapsible.vue')['default']
    ContactForm: typeof import('./../components/ContactForm.vue')['default']
    CssChart: typeof import('./../components/CssChart.vue')['default']
    CvComp: typeof import('./../components/CvComp.vue')['default']
    CvLinks: typeof import('./../components/CvLinks.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    Heading: typeof import('./../components/Heading.vue')['default']
    'IconCi:moon': typeof import('~icons/ci/moon')['default']
    'IconCi:paperPlane': typeof import('~icons/ci/paper-plane')['default']
    'IconCi:sun': typeof import('~icons/ci/sun')['default']
    IconFa6BrandsWeebly: typeof import('~icons/fa6-brands/weebly')['default']
    IconMaterialSymbolsStarRounded: typeof import('~icons/material-symbols/star-rounded')['default']
    'IconMdi:chevronDown': typeof import('~icons/mdi/chevron-down')['default']
    'IconMdi:download': typeof import('~icons/mdi/download')['default']
    'IconMdi:email': typeof import('~icons/mdi/email')['default']
    'IconMdi:github': typeof import('~icons/mdi/github')['default']
    'IconMdi:linkedin': typeof import('~icons/mdi/linkedin')['default']
    'IconMdi:mapMarkerRadiusOutline': typeof import('~icons/mdi/map-marker-radius-outline')['default']
    'IconMdi:send': typeof import('~icons/mdi/send')['default']
    'IconMdi:star': typeof import('~icons/mdi/star')['default']
    IconMdiGithub: typeof import('~icons/mdi/github')['default']
    IconMdiGithubBox: typeof import('~icons/mdi/github-box')['default']
    IconMdiHeadHeart: typeof import('~icons/mdi/head-heart')['default']
    IconMdiHeart: typeof import('~icons/mdi/heart')['default']
    IconMdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    IconMdiSchool: typeof import('~icons/mdi/school')['default']
    IconMdiSquareInc: typeof import('~icons/mdi/square-inc')['default']
    IconMdiTwitter: typeof import('~icons/mdi/twitter')['default']
    IconTablerViewfinder: typeof import('~icons/tabler/viewfinder')['default']
    ListPosts: typeof import('./../components/ListPosts.vue')['default']
    ListProjects: typeof import('./../components/ListProjects.vue')['default']
    MarkdownPage: typeof import('./../components/MarkdownPage.vue')['default']
    Navigation: typeof import('./../components/Navigation.vue')['default']
    NpmPackage: typeof import('./../components/NpmPackage.vue')['default']
    Popper: typeof import('./../components/Popper.vue')['default']
    PrintUrlLabel: typeof import('./../components/PrintUrlLabel.vue')['default']
    ProjectCard: typeof import('./../components/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('./../components/Spinner.vue')['default']
    TerminalWindow: typeof import('./../components/TerminalWindow.vue')['default']
    TransitionCollapse: typeof import('./../components/TransitionCollapse.vue')['default']
    WiggleAnimation: typeof import('./../components/WiggleAnimation.vue')['default']
  }
}
